///////////////////////////////////////////////////////////////////////////////
// TcCppTestLibInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcCppTestLibServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
