///////////////////////////////////////////////////////////////////////////////
// TcCppTestLibServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcCppTestLib = 0x3F000000;
#define SRVNAME_TCCPPTESTLIB "TcCppTestLib"

///<AutoGeneratedContent id="ClassIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>


