///////////////////////////////////////////////////////////////////////////////
// ExampleInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ExampleServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
