///////////////////////////////////////////////////////////////////////////////
// ExampleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Example = 0x3F000000;
#define SRVNAME_EXAMPLE "Example"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ExampleCExample = {0x490cf7fa,0x0e0f,0x440f,{0xba,0x90,0x51,0xab,0xec,0xe2,0xfe,0x84}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
